### ISSUE TITLE
Crash in r_coll

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#131]
Back trace:
```
#0  0xb6cefc63 in __memmove_ia32 () from /lib/libc.so.6
#1  0x08171573 in __copy_m<std::array<float, 3u> > (__result=<optimized out>, __last=<optimized out>, 
    __first=0xaf06a008) at /usr/include/c++/4.9.2/bits/stl_algobase.h:378
#2  __copy_move_a<false, std::array<float, 3u>*, std::array<float, 3u>*> (__result=<optimized out>, 
    __last=<optimized out>, __first=0xaf06a008) at /usr/include/c++/4.9.2/bits/stl_algobase.h:396
#3  __copy_move_a2<false, __gnu_cxx::__normal_iterator<std::array<float, 3u>*, std::vector<std::array<float, 3u> > >, std::array<float, 3u>*> (__result=<optimized out>, __last=..., __first=...)
    at /usr/include/c++/4.9.2/bits/stl_algobase.h:434
#4  copy<__gnu_cxx::__normal_iterator<std::array<float, 3u>*, std::vector<std::array<float, 3u> > >, std::array<float, 3u>*> (__result=<optimized out>, __last=..., __first=...)
    at /usr/include/c++/4.9.2/bits/stl_algobase.h:466
#5  RenderDebugDrawer::render (this=0x8215a40 <debugDrawer>) at src/render.cpp:1283
#6  0x08175e99 in Render::drawListDebugLines (this=0x821ab80 <renderer>) at src/render.cpp:1088
#7  0x081b1bce in Engine_Display () at src/main_SDL.cpp:451
#8  0x081b1c90 in Engine_Display () at src/main_SDL.cpp:502
#9  Engine_Frame (time=<optimized out>) at src/main_SDL.cpp:501
#10 0x080e7c26 in main () at src/main_SDL.cpp:351
```

**Comment by stohrendorf** [comment]
Should be working now.

**Comment by vvs-** [comment]
Yes, it's fixed. Thanks.
