### ISSUE TITLE
Crash when trying to grab movable block

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#189]
```
#0  0x082c79ad in RoomSector::checkPortalPointer (this=0x0) at src/world.cpp:201
#1  0x0831b7ce in Character::checkTraverse (this=0xb9453e4, obj=0xae2c85c)
    at src/character_controller.cpp:1847
#2  0x08302812 in State_Control_Lara (character=0xb9453e4, ss_anim=0xb945478)
    at src/anim_state_control.cpp:1374
#3  0x0831bb25 in Character::applyCommands (this=0xb9453e4) at src/character_controller.cpp:1887
#4  0x082da648 in Game_Frame (time=0.0161514282) at src/game.cpp:831
#5  0x0830df31 in Engine_Frame (time=0.0161514282) at src/main_SDL.cpp:553
#6  0x0830da55 in main () at src/main_SDL.cpp:402
```

**Comment by vvs-** [comment]
There is no more crash but it still doesn't work.
